version: '2'
services:
    blogreact-app:
        image: blogreact
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://blogreact-postgresql:5432/blogreact
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blogreact-postgresql:
        extends:
            file: postgresql.yml
            service: blogreact-postgresql
